In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./data/house_price.csv')

In [5]:
df.head()

   bedrooms  sq_meter neighborhood  sales_price
0         3       200  Normalville       250000
1         2        80    Cool Town       300000
2         2        85  Normalville       150000
3         1         5  Normalville        78000
4         4       200     Skid Row       150000

In [6]:
df_filtered = df['sq_meter'] > 82
df_filtered.head()

0     True
1    False
2     True
3    False
4     True
Name: sq_meter, dtype: bool

In [7]:
df_filtered = df[df['sq_meter'] > 82]
df_filtered.head()

   bedrooms  sq_meter neighborhood  sales_price
0         3       200  Normalville       250000
2         2        85  Normalville       150000
4         4       200     Skid Row       150000