##  Exercises for Pandas and Jupyter Notebook

In [2]:
import pandas as pd

1. Load and Display Data
    * Read the CSV file house_price.csv and display the first 2 rows.

In [5]:
df = pd.read_csv('./data/house_price.csv')
df.head(2)

   bedrooms  sq_meter neighborhood  sales_price
0         3       200  Normalville       250000
1         2        80    Cool Town       300000

2. Show Statistical Summary
    * Display a statistical summary of the dataset to see the mean, standard 
deviation, minimum and maximum values, etc.

In [6]:
df.describe()

       bedrooms    sq_meter    sales_price
count  5.000000    5.000000       5.000000
mean   2.400000  114.000000  185600.000000
std    1.140175   84.661089   88525.702482
min    1.000000    5.000000   78000.000000
25%    2.000000   80.000000  150000.000000
50%    2.000000   85.000000  150000.000000
75%    3.000000  200.000000  250000.000000
max    4.000000  200.000000  300000.000000

3. Filter Data
    * Filter the dataset to show only houses with more than 2 bedrooms.

In [8]:
df_2up = df[df['bedrooms']>2]
df_2up.head()

   bedrooms  sq_meter neighborhood  sales_price
0         3       200  Normalville       250000
4         4       200     Skid Row       150000

4. Sort Data
    * Sort the dataset based on the sales price in ascending order.

In [21]:
df = df.sort_values(by='sales_price')
print(df)

   bedrooms  sq_meter neighborhood  sales_price     price_sqm
3         1         5  Normalville        78000  15600.000000
2         2        85  Normalville       150000   1764.705882
4         4       200     Skid Row       150000    750.000000
0         3       200  Normalville       250000   1250.000000
1         2        80    Cool Town       300000   3750.000000

5. Calculate Average Sales Price
    * Calculate the average sales price for all houses.

In [11]:
df_av_sales_price = df['sales_price'].mean()
print(f'Average sales price: {df_av_sales_price}')

Average sales price: 185600.0

6. Add a New Column
    * Add a new column that shows the price per square meter.

In [22]:
df['price_sqm'] = df['sales_price'] / df['sq_meter']
df.price_sqm = df.price_sqm.round(2)
print(df)

   bedrooms  sq_meter neighborhood  sales_price  price_sqm
3         1         5  Normalville        78000   15600.00
2         2        85  Normalville       150000    1764.71
4         4       200     Skid Row       150000     750.00
0         3       200  Normalville       250000    1250.00
1         2        80    Cool Town       300000    3750.00

7. Group Data
    * Group the dataset by neighborhood and calculate the average sales price for 
each neighborhood.

In [25]:
grouped_data = df.groupby('neighborhood')['sales_price'].mean().round(2)
print(grouped_data)

neighborhood
Cool Town      300000.00
Normalville    159333.33
Skid Row       150000.00
Name: sales_price, dtype: float64

8. Visualize Data
    * Create a simple bar plot that shows the average sales price per neighborhood.

In [26]:
import matplotlib.pyplot as plt
grouped_data.plot()
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

9. Find Maximum Values
    * Find the house with the highest sales price.

10. Export Data
    * Export the manipulated DataFrame to a new CSV file.